name: Daily Commit

on:
  schedule:
    - cron: "0 18 * * *" # Runs every day at 12:00 AM IST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make a commit
        run: |
          echo "$(date)" >> daily-log.txt
          git config user.name "DipanshuA"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add daily-log.txt
          git commit -m "Daily update" || exit 0

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
